export default function Contact() {
  return (
    <main className='main'>
      <header className='header'>CONTACT</header>
      <section className='section'>
        <div>GitHub</div>
        <div>Blog</div>
        <div>email</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
      </section>
    </main>
  );
}
