export default function Contact() {
  return (
    <section className='section'>
      <header className='section-title'>CONTACT</header>
      <p className='section-content'>
        <div>GitHub</div>
        <div>Blog</div>
        <div>email</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
        <div>Phone Number</div>
      </p>
    </section>
  );
}
